# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  config.vm.boot_timeout = 900
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2

    # v.memory = 1024
    # v.cpus = 1
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    
    app.vm.network "forwarded_port", guest: 9200, host: 9200,
      auto_correct: true, id: "test-app-80"
      app.vm.network "forwarded_port", guest: 5044, host: 5044,
      auto_correct: true, id: "test-app-443"
      
    app.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ELK.yml"
      ansible.become = true
      ansible.become_user = "root"
    end

  end
  
end
