---
#
# Installing Java 8
#

# Add the Java repo

- name: install java8 jre
  apt: 
    name: openjdk-8-jre 
    update_cache: yes 
    state: latest
    
- name: install java8 jdk
  apt: 
    name: openjdk-8-jdk 
    update_cache: yes 
    state: latest
