- name: install logstash
  apt: name=logstash update_cache=yes state=latest

- name: start and enable logstash
  systemd:
    name: logstash
    state: started
    enabled: yes

- name: add input config file for logstash
  template:
    src: beats-input.conf.j2
    dest: /etc/logstash/conf.d/beats-input.conf
    owner: root 
    group: root

- name: add input config file for logstash
  template:
    src: elastic-search-output.conf.j2
    dest: /etc/logstash/conf.d/elastic-search-output.conf
    owner: root 
    group: root