---
#
# Installing Elasticsearch
#
- name: Install elasticsearch
  yum:
    name: elasticsearch
    update_cache: yes

# line in file code
- name: Updating the config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'cluster.name:'
   line: 'cluster.name: my-application'

- name: Updating the config file
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'node.name:'
   line: 'node.name: master'

- name: Updating the config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   line: 'node.master: true'

- name: Updating the config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   line: 'node.data: false'

- name: Updating the config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: [_local_, {{ master_node_private_ip }}]'

- name: Updating the config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'cluster.initial_master_nodes:'
   line: 'cluster.initial_master_nodes: ["{{ master_node_private_ip }}"]'

# Update Elasticsearch port in config file 

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'

- name: enable elastic search service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes